import game
glolfgame = game.SingleHole()
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
print(glolfgame.update())
print(glolfgame.printboard())
